### ISSUE TITLE
Not maintained anymore?

### ISSUE THREAD

**Issue by mknxio** [highcharts/pattern-fill#35]
> https://www.highcharts.com/blog/extension/pattern-fill/

I would like to know if by **not actively maintained** you mean minimised development or no development at all? And why is this plugin not actively maintained?
You started this plugin, which is used by many Highcharts users, but you stopped its development? Why?

Thanks for your response.

**Comment by TorsteinHonsi** [comment]
Yes, it is still maintained. The official landing page for the plugin is at https://www.highcharts.com/products/plugin-registry/single/9/Pattern-Fill , I'll find out where that blog page comes from and why it says "Not actively maintained".
