### ISSUE TITLE
Image pattern does not use opacity setting

### ISSUE THREAD

**Issue by yunicz** [highcharts/pattern-fill#39]
Hi, there is a little bug in this plugin, if I want to use image pattern with opacity it is not possible. I can prepare a fix for this, it's straightforward. 
```
// Image pattern
 } else if (options.image) {
	if (animate) {
		this.image(
		       options.image, 0, 0, width, height, function () {
		              // Onload
                              // Here in the onload handler check for options.opacity is needed 
		              this.animate({ opacity: 1 }, animate);
		              H.removeEvent(this.element, 'load');
		          }
		      ).attr({ opacity: 0 }).add(pattern);
	} else {
	      this.image(options.image, 0, 0, width, height).add(pattern);
	}
}

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng Does this apply to the new module too?

**Comment by oysteinmoseng** [comment]
@TorsteinHonsi Yes and no, it would work with images now except animation overrides it. I'll take a look.

**Comment by oysteinmoseng** [comment]
Fixed in https://github.com/highcharts/highcharts/commit/1502c518736112534b7f11c8d397bdbd595db766
